schema_version = "1.0.0"

id = "TrackMe"
version = "0.0.2"
name = "Track Me"
tagline = "Tracks time that you spend on each blend file"
maintainer = "Danylo Hrechyshkin"
type = "add-on"
tags = ["System"]
blender_version_min = "4.5.3"
license = ["SPDX:GPL-3.0-or-later"]